# @package _global_

defaults:
  - override /data: mv_recon

name: mv_recon

wid3r:
  pretrained_model_name_or_path: pretrained_weights/wid3r.bin

eval_datasets:
  - ScanNetpp
  - MP3D
  - Stanford2D3D

no_crop: True
width: 518
height: 336

device: cuda

verbose: False

seed: 42

save_suffix: null
